api/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, skip: :all

  devise_scope :user do
    scope '/api/v1/users', defaults: { format: :json } do
      post   '/sign_in',       to: 'api/v1/users/sessions#create'
      delete '/sign_out',      to: 'api/v1/users/sessions#destroy'
      post   '/sign_up',       to: 'api/v1/users/registrations#create'
      put    '/account_update', to: 'api/v1/users/registrations#update'
    end
  end

  if Rails.env.development?
    mount Rswag::Api::Engine => '/api-docs'
    mount Rswag::Ui::Engine => '/api-docs'
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resources :favorites, only: %i[index create destroy]
    end
  end
end

api/app/views/admin/_dashboard.html.erb
<div class="dashboard-page">
	<div class="panel-container activities">
		<h2 class="panel-title"><%= I18n.t('active_admin.latests_updates') %></h2>

		<ul class="panel-content">
			<% Product.order(updated_at: :desc).limit(5).each do |product| %>
				<li>
					<%= link_to product.name, admin_product_path(product) %>
					<%= I18n.t('active_admin.updated_at', date: product.updated_at ) %>
				</li>
			<% end %>
		</div>
	</div>

	<div class="panel-container statistics">
		<h2 class="panel-title"><%= I18n.t('active_admin.statistics') %></h2>

		<div class="stat-container">
			<div class="stat-bloc">
				<div class="stat-icon user"><%= fa_icon 'user' %></div>
				<p class="stat-number">
					<span><%= User.count %></span>
					<span><%= I18n.t('active_admin.navigation.users') %></span>
				</p>
			</div>

			<div class="stat-bloc">
				<div class="stat-icon product"><%= fa_icon 'leaf' %></div>
				<p class="stat-number">
					<span><%= Product.count %></span>
					<span><%= I18n.t('active_admin.navigation.products') %></span>
				</p>
			</div>
		</div>
	</div>
</div>